name: passwordmanager
description: A simple passwordmanager

publish_to: 'none'

version: 2.1.0+1

environment:
  sdk: '>=3.1.0-67.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  http: ^1.2.0
  pointycastle: ^4.0.0
  base32: ^2.1.3
  ntp: ^2.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  file_picker: ^10.2.0
  provider: ^6.1.5
  flutter_svg: ^2.2.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lightLogo.svg
    - assets/darkLogo.svg