name: passwordmanager
description: A simple passwordmanager

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.1.0-67.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.1.0

  pointycastle: ^3.7.3
  base32: ^2.1.3

  path_provider: ^2.1.1
  shared_preferences: ^2.1.1
  file_picker: ^5.2.11
  provider: ^6.0.5
  flutter_svg: ^2.0.6
  package_info_plus: ^4.0.1
  url_launcher: ^6.1.11
  firedart: ^0.9.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lightLogo.svg
    - assets/darkLogo.svg